didi/Hummer

- .gitignore
- README.md
- android/README.md
- ios/README.md
> docs: update readme

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
ISSUE_TEMPLATE YAML front matter not work.
[Internal] [Fixed] - Fix ISSUE_TEMPLATE YAML front matter not work
None
> fix: ISSUE_TEMPLATE.md error

- iOS/Hummer/Classes/Core/Layout/Manager/HMUIManager.m
Fix HMUIManager preserveOrigin logic error
[iOS] [Fixed] - Fix HMUIManager preserveOrigin logic oldOrigin.y plus origin.x
None
close #20
> fix: HMUIManager origin.y plus oldOrigin.x error

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
(cherry picked from commit 59112237eaf4129950e97b161f2ff0c98eb73e18)
close #17
> feat: Add config.yml

- Hummer.podspec
- iOS/Hummer/Classes/Engine/HMBaseExecutor.h
- iOS/Hummer/Classes/Engine/HMBaseExecutor.m
- iOS/Hummer/Classes/Engine/HMBaseValue.h
- iOS/Hummer/Classes/Engine/HMBaseValue.m
- iOS/Hummer/Classes/Engine/HMBaseWeakValue.h
- iOS/Hummer/Classes/Engine/HMBaseWeakValue.m
- iOS/Hummer/Classes/Engine/HMExceptionModel.h
- iOS/Hummer/Classes/Engine/HMExceptionModel.m
| Fixed Issues?            | Assign #33 
| Major: Breaking Change?  | Yes
| Tests Added + Pass?      | No 
完成抽象 JSContext、JSValue、JSManagedValue 和实现 ExceptionModel
> feat(iOS): Add Abstract JSContext, JSValue and ExceptionModel

- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.m
- iOS/Hummer/Classes/Engine/HMBaseValue.h
- iOS/Hummer/Classes/Engine/HMBaseWeakValueProtocol.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor+Private.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue+Private.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCValue.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.m
| Fixed Issues?            | Assign #33 
> feat(iOS): Implement JavaScriptCore JSValue

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMCompatibleRenderObject.m
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
- iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
| Fixed Issues?            | Fixes #41, Fixes #42 
> fix(iOS): HMCompatibleRenderObject affect UIScrollView and hm_sizeThatFits:

- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
| Fixed Issues?            | Assign #33 
> fix(iOS): JavaScriptCore finalize callback assert crash

- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.m
| Fixed Issues?            | Assign #33 
> fix(iOS): JavaScriptCore finalize callback crash

- iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPager.m
| Fixed Issues?            | Fixes #46 
| Patch: Bug Fix?          |  Yes
| Minor: New Feature?      |  NO
> fix(iOS)：ViewPager setCurrentItem bug

- iOS/Hummer/Classes/Component/HMConsole.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
> fix: console.log print twice

- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
- iOS/Hummer/Classes/Engine/HMBaseValue.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
| Fixed Issues?            | Fixes #54 
> feat(iOS): Add number string force convert

- iOS/Hummer/Classes/Component/Animation/TransitionAnimation/HMTransitionAnimationConverter.m
- iOS/Hummer/Classes/Component/Views/View/UIView+HMAttribute.h
- iOS/Hummer/Classes/Component/Views/View/UIView+HMAttribute.m
- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.h
- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
| Fixed Issues?            | Fixes #51  
| Patch: Bug Fix?          |  Yes
> fix(iOS): fixed bugs

- .gitignore
- README.md
修改 ignore 文件，增加 node_modules 的过滤；
修改 Readme 文件，增加关联仓库的文档。
> chore: 修改 Readme ，增加关联仓库文档

- iOS/Hummer/Classes/Component/Controller/HMViewController.m
> chore(iOS): Remove comment

- iOS/Hummer/Classes/Component/NotifyCenter/HMNotifyCenter.m
- iOS/Hummer/Classes/Component/Views/Scroller/HMScrollView.m
> refactor(iOS): HMNotification

- android/gradle.properties
> feat(Android): android release version: 0.3.16

- iOS/Hummer/Classes/Component/Controller/HMViewController.m
- iOS/Hummer/Classes/Component/NotifyCenter/HMNotifyCenter.m
- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/Core/Utility/HMLayoutUtils.m
| Fixed Issues?            | Fixes #33 
> fix(iOS): Inner code sync

- iOS/Hummer/Classes/Event/Base/HMBaseEvent.m
| Fixed Issues?            | Fixes #64  
> fix：Object.assgin() cause event(function) invalid in tenon2

- android/gradle.properties
- android/hummer-component/src/main/java/com/didi/hummer/component/imageview/Image.java
- android/hummer-component/src/main/java/com/didi/hummer/component/imageview/ImageRenderUtil.java
- android/hummer-component/src/main/java/com/didi/hummer/component/scroller/Scroller.java
- android/hummer-sdk/build.gradle
- android/hummer-sdk/src/main/AndroidManifest.xml
- android/hummer-sdk/src/main/java/com/didi/hummer/HummerSDK.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/IImageLoaderAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/ImageSizeCallback.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/impl/DefaultImageLoaderAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/location/impl/DefaultLocationAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/module/notifycenter/NotifyCenter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/AssetsUtil.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/FileUtil.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/IntentUtils.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/LocationUtils.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/PermissionConstants.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/PermissionUtils.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/Utils.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/UtilsTransActivity.java
- android/hummer-sdk/src/main/res/values-v21/values-v21.xml
- android/hummer-sdk/src/main/res/values/values.xml
| Fixed Issues?            | `Fixes #67, Fixes #79` 
> fix(Android): 日常bugfix

- iOS/ExampleTests/HMShadowViewTests.swift
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMYogaUtility.cpp
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMYogaUtility.h
- iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
- iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.m
> fix(iOS): Error

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
> fix(iOS): Build error

- tenon/lerna.json
- tenon/package.json
> chore: 修改 tenon lerna 的配置

- examples/tenon-vue/src/main/app.vue
- tenon/packages/tenon-utils/src/style/transformer/color.ts
| Fixed Issues?            | `Fixes #86 ` 
> fix: 修复颜色色值 #eee 不生效的情况

- android/gradle.properties
- android/hummer-component/src/main/java/com/didi/hummer/component/scroller/HorizontalScroller.java
- android/hummer-component/src/main/java/com/didi/hummer/component/scroller/Scroller.java
- android/hummer-core/build.gradle
- android/hummer-demo-app/build.gradle
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/scriptloader/impl/DefaultScriptLoaderAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/context/HummerContext.java
- android/hummer-sdk/src/main/java/com/didi/hummer/render/component/anim/BasicAnimation.java
> feat(Android): android release version: 0.3.18

- iOS/Hummer/Classes/Component/Animation/HMCAAnimation+Internal.h
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
| Fixed Issues?            | Fixes #91  
> fix：env.copy crash

- iOS/builtin/src/utility.ts
| Fixed Issues?            | Fixes #93  
> fix：this is undefine

- iOS/Hummer/Classes/Component/Animation/BasicAnimationImp/HMCABasicAnimation.m
- iOS/Hummer/Classes/Component/Animation/HMCAAnimation.m
- iOS/Hummer/Classes/Component/Animation/Transform/HMTransform.h
- iOS/Hummer/Classes/Component/Animation/Transform/HMTransform.m
[Feature: iOS平台 倾斜skew动画支持 ](https://github.com/didi/Hummer/issues/98)  
| Fixed Issues?            | `Fixes #98` 
| Patch: Bug Fix?          | NO
> add: iOS add skew animation

- android/gradle.properties
- android/hummer-component/src/main/java/com/didi/hummer/component/dialog/Dialog.java
- android/hummer-core/src/main/java/com/didi/hummer/core/engine/jsc/JSCCallback.java
- android/hummer-core/src/main/jni/qjs/hummer/JavaScriptRuntime.cpp
- android/hummer-demo-app/src/main/java/com/didi/hummer/demo/MyHummerFragmentActivity.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/navigator/impl/ActivityStackManager.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/navigator/impl/DefaultNavigatorAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/render/component/view/HMBase.java
- android/hummer-sdk/src/main/java/com/didi/hummer/render/event/EventManager.java
- android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/PermissionUtils.java
- android/hummer/src/main/java/com/didi/hummer/HummerActivity.java
| Patch: Bug Fix?          |  Yes
> feat(Android): android bugfix

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
> fix(iOS): exceptionHandler add namespace

- examples/tenon-vue/package.json
Modify  Dependencies Of Tenon Example!
> Docs/example: modify tenon example

- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal+Private.h
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal+Private.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/Interceptor/HMInterceptor.h
- iOS/Hummer/Classes/Interceptor/HMInterceptor.m
- iOS/Hummer/Classes/Interceptor/HMJSLoadInterceptor.h
| Fixed Issues?            |  Fixes #111  
| Patch: Bug Fix?          | NO
> feat：support  evaluateScript

- android/hummer-sdk/build.gradle
> fix: 移除com.facebook.yoga:proguard-annotations依赖

- examples/hummer/src/Comp_ViewPager.js
- examples/hummer/src/Test_TestExportModel.js
> chore(Android): 更新测试用例

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
| Fixed Issues?            | Fixes #79 
> feat(iOS): Send console to CLI by WebSocket

- examples/tenon-vue/src/component-button/app.vue
- tenon/packages/tenon-compiler/src/index.ts
- tenon/packages/tenon-compiler/src/transforms/transformProps.ts
| Fixed Issues?            | Fixes #146  
| Tests Added + Pass?      | Yes 
支持click事件编译成tap事件
> fix(compiler): 支持click自动转换tap事件

- iOS/Hummer/Classes/Component/Views/View/UIView+HMEvent.m
- iOS/Hummer/Classes/Event/Gesture/HMTapEvent.m
| Fixed Issues?            | Fixes #157 
> feat(iOS): Add rawX/Y

- iOS/Hummer/Classes/Component/Views/View/HMAttributesItem.m
> fix(iOS): Crash

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMCompatibleRenderObject.m
> feat(iOS): Image control auto resize

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMCompatibleRenderObject.m
| Fixed Issues?            | Fixes #160 
> fix(iOS): Image location calculate add missing condidation

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
| Fixed Issues?            | Fixes #79 
> fix(iOS): Release build error

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
> fix(iOS): - hm_sizeThatFits: Add position: 'absolute' case

- examples/tenon-vue/src/common/assets/css/common.less
- examples/tenon-vue/src/main/assets/menu.js
- examples/tenon-vue/src/style-basic/app.vue
- examples/tenon-vue/src/style-layout/app.vue
- examples/tenon-vue/src/style-layout/entry.js
- tenon/CHANGELOG.md
- tenon/lerna.json
- tenon/packages/tenon-compiler/CHANGELOG.md
- tenon/packages/tenon-compiler/package.json
- tenon/packages/tenon-store/CHANGELOG.md
- tenon/packages/tenon-store/package.json
- tenon/packages/tenon-utils/CHANGELOG.md
- tenon/packages/tenon-utils/package.json
- tenon/packages/tenon-utils/src/style/common/utils.ts
- tenon/packages/tenon-utils/src/style/transformer/flex.ts
- tenon/packages/tenon-vue/CHANGELOG.md
- tenon/packages/tenon-vue/package.json
- tenon/packages/tenon/CHANGELOG.md
- tenon/packages/tenon/package.json
| Fixed Issues?            | Fixes #141 
| Patch: Bug Fix?          | YES
| Tests Added + Pass?      | Yes 
修复 `flex:1`在 hummer 环境与浏览器预期不一致的问题
> Feature/dev tenon：修复 Flex 1在hummer 环境与浏览器预期不一致的问题

- examples/hummer/src/Comp_ViewPager.js
> fix(Android): 修复ViewPager用例bug

- android/ReleaseNotes.md
- android/gradle.properties
> feat(Android): android release version: 0.3.21

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
> fix(iOS): margin reject auto

- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
> fix(iOS): Add Yoga prefix

- Hummer.podspec
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
> fix(iOS): sizeThatFits function call error

- examples/tenon-react/src/benchmark-scroller/App.jsx
- examples/tenon-react/src/common/components/DemoItem.jsx
- examples/tenon-react/src/common/components/PageItem.jsx
- examples/tenon-react/src/component-button/App.jsx
- examples/tenon-react/src/component-image/App.jsx
- examples/tenon-react/src/component-image/components/DemoItem.jsx
- examples/tenon-react/src/component-input/App.jsx
- examples/tenon-react/src/component-scroller/App.jsx
- examples/tenon-react/src/component-switch/App.jsx
- examples/tenon-react/src/component-text/App.jsx
- examples/tenon-react/src/component-textarea/App.jsx
- examples/tenon-react/src/component-view/App.jsx
- examples/tenon-react/src/hook-test/components/UseCallbackComponent.jsx
- examples/tenon-react/src/hook-test/components/UseEffectComponent.jsx
- examples/tenon-react/src/hook-test/components/UseReducerComponent.jsx
- examples/tenon-react/src/hook-test/components/UseStateComponent.jsx
- examples/tenon-react/src/index/App.jsx
- examples/tenon-react/src/main/App.jsx
- examples/tenon-react/src/main/components/ListItem.jsx
- tenon/packages/tenon-core/src/nodes/Base.ts
- tenon/packages/tenon-react/src/hostConfig/utils.ts
> Tenon React Support ClassName

- iOS/Hummer/Classes/Core/Bridge/HMDebug.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/DevTools/HMDevPageInfo/HMDevToolsJSCallerExcutor.m
- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.h
> feat(iOS): Add HMDEBUG macro

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
> feat(iOS): Export hm_context

- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
> fix(iOS): Add missing code

- iOS/Hummer/Classes/DevTools/HMDevToolsEntryView.m
| Minor: New Feature?      |  
| Tests Added + Pass?      |  
修复某些情况下工具栏不能正确显示
> fix(devtools):修复某些情况下工具栏不能正确显示

- examples/tenon-react/src/animation-basic/App.jsx
- examples/tenon-react/src/animation-basic/App.less
- examples/tenon-react/src/animation-basic/common/animation.js
- examples/tenon-react/src/animation-basic/entry.js
- examples/tenon-react/src/animation-keyframe/App.jsx
- examples/tenon-react/src/animation-keyframe/App.less
- examples/tenon-react/src/animation-keyframe/common/animation.js
- examples/tenon-react/src/animation-keyframe/entry.js
- examples/tenon-react/src/animation-steps/App.jsx
- examples/tenon-react/src/animation-steps/App.less
- examples/tenon-react/src/animation-steps/common/animation.js
- examples/tenon-react/src/animation-steps/entry.js
- examples/tenon-react/src/animation-transition/App.jsx
- examples/tenon-react/src/animation-transition/App.less
- examples/tenon-react/src/animation-transition/entry.js
- examples/tenon-react/src/grammar/components/CreateRefComponent.jsx
- examples/tenon-react/src/main/assets/menu.js
- examples/tenon-vue/src/event/app.vue
- tenon/packages/tenon-core/src/nodes/Base.ts
- tenon/packages/tenon-react/README.md
- tenon/packages/tenon-react/src/hook/index.ts
- tenon/packages/tenon-react/src/hostConfig/utils.ts
- tenon/packages/tenon-vue/src/runtime/nodes/Base.ts
- tenon/rollup.config.js
-[U] Tenon React 支持基础动画
-[U] Tenon React 支持关键帧动画
-[U] Tenon React 支持次序动画
-[U] 添加 Tenon React 动画 Demo
> Tenon React Support Animation

- iOS/Hummer/Classes/Component/Location/HMLocation.m
> fix(iOS): HMLocation use GCJ02 instead of native WGS84

- android/ReleaseNotes.md
- android/gradle.properties
| Fixed Issues?            | No 
> feat(Android): android release version: 0.3.23

- iOS/Hummer/Classes/Component/Views/Label/HMLabel.m
- iOS/Hummer/Classes/Component/Views/View/HMAttributesItem.h
- iOS/Hummer/Classes/Core/Utility/HMConverter.h
- iOS/Hummer/Classes/Core/Utility/HMConverter.m
> Text 组件添加长按复制、垂直方向控制属性

- android/hummer-component/src/main/java/com/didi/hummer/component/text/Text.java
- android/hummer-sdk/src/main/java/com/didi/hummer/render/style/HummerStyleUtils.java
- examples/hummer/src/Comp_Text.js
> Text组件增加 垂直居中属性 && 长按复制

- iOS/Hummer/Classes/Component/Views/ImageView/HMImageView.h
- iOS/Hummer/Classes/Component/Views/ImageView/HMImageView.m
- iOS/Hummer/Classes/Core/Manager/HMImageManager.m
- iOS/Hummer/Classes/Core/Manager/ImageLoader/ConcreteLoader/HMBase64ImageLoader.m
- iOS/Hummer/Classes/Core/Manager/ImageLoader/ConcreteLoader/HMLocalImageLoader.m
- iOS/Hummer/Classes/Core/Manager/ImageLoader/HMImageLoaderDefine.h
- iOS/Hummer/Classes/Core/Manager/ImageLoader/Operation/HMImageDownloadOperation.m
> feat(iOS): Image loading success or failure callback

- android/hummer-component/src/main/java/com/didi/hummer/component/canvas/CanvasContext.java
- android/hummer-component/src/main/java/com/didi/hummer/component/canvas/CanvasDrawHelperView.java
- android/hummer-component/src/main/java/com/didi/hummer/component/canvas/CanvasPath.java
- android/hummer-component/src/main/java/com/didi/hummer/component/canvas/CanvasView.java
- examples/hummer/src/Comp_Canvas.js
| Tests Added + Pass?      | Yes 
1. 增加了 hummer 对 canvas 自定义画图的支持，在component下增加canvas包，增加了CanvasView
2. 增加了Comp_Canvas.js 展示，其中包括了几乎所有可用的方法，android ios 两端都有正常展示及对齐
> Feat add camvas

- iOS/Hummer/Classes/Core/Bridge/NSObject+Hummer.m
| Patch: Bug Fix?          | NO
| Minor: New Feature?      | NO
| Tests Added + Pass?      | NO
避免重复创建 `HMJSCStrongValue` 对象！
> 【iOS】Avoid create `HMJSCStrongValue` repeatedly

- iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
- iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.m
> feat(iOS): Add HMSizeThatFitsMode change function

- examples/hummer/playground/src/common/CommonLayout.ts
- examples/hummer/playground/src/common/CommonResource.ts
> feat(TS): Playground 新增【最佳实践】和【小游戏】模块

- iOS/Hummer/Classes/Core/HMBorderDrawing.m
| Tests Added + Pass?      | NO 
使用 `UIGraphicsImageRenderer `来绘制，提高性能。
> feat(iOS): Optimize iOS render drawing

- iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPager.m
- iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPagerCell.m
> fix(iOS): ViewPager cell not same as ViewPager

- iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPager.m
- iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPagerCell.m
- iOS/Hummer/Classes/Component/WebSocket/HMWebSocket.m
> fix(iOS): WebSocket should wrap with `data`

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
> feat(iOS): Add hummerUrl which is `hummer://host/path/file.ext` format

- iOS/Hummer/Classes/Component/Animation/TransitionAnimation/HMTransitionAnimationConverter.m
> feat(iOS): transition animation convert to doubleValue instead of integerValue

- iOS/Hummer/Classes/Event/View/HMScrollEvent.m
> fix(iOS): Scroll event parameter name update

- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.h
- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
> fix(iOS): memory error

- iOS/Hummer/Classes/Core/Bridge/NSObject+Hummer.m
> fix(iOS): hmValue compatibility

- Hummer.podspec
> fix(iOS): podspec

- Hummer.podspec
- iOS/Hummer/Classes/Component/WebSocket/HMWebSocket.m
> chore(iOS): Downgrade SocketRocket

- android/ReleaseNotes.md
- android/gradle.properties
- android/hermes-debugger/upload.gradle
- android/hummer-annotation/upload.gradle
- android/hummer-compiler/upload.gradle
> chore(Android): android release version: 0.4.2

- iOS/Hummer/Classes/Core/Utility/HMLayoutUtils.m
feat : 对iOS侧的 getRect方法优化：增加四个参数回传，获取相对于window的位置信息。
* windowLeft:number      控件左边界相对于屏幕左边界的值
* windowRight:number    控件右边界相对于屏幕左边界的值
* windowTop:number       控件上边界相对于屏幕上边界的值
* windowBottom:number 控件下边界相对于屏幕上边界的值
> feat(iOS): getRect方法优化：增加四个参数回传，获取相对于window的位置信息。

- tenon/packages/tenon-dev-tool/src/index.ts
- tenon/packages/tenon-dev-tool/src/utils.ts
> feat: hummer ts 视图调试

- iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
- iOS/Hummer/Classes/Core/HMView.m
> fix(iOS): gradient backgroundColor should disable animation

- iOS/Hummer/Classes/Core/Bridge/NSObject+Hummer.h
- iOS/Hummer/Classes/Core/Bridge/NSObject+Hummer.m
- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
- iOS/Hummer/Classes/Engine/N-API/HMJSExecutor.m
> fix(iOS): hmValue is strong readonly value, weak value will set by setter

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
> fix(iOS): hummerUrl will use fileName when the hummerUrl is empty

- tenon/packages/tenon-vue/src/runtime/nodes/Base.ts
| Minor: New Feature?      |  
> bugfix: 修复scoped的父组件给自定义组件设置class后样式不生效的问题

- iOS/Hummer/Classes/Component/Views/ListView/HMRecycleListView.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal+Private.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsLogger/HMDevToolsLoggerViewController.m
- iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.h
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
- iOS/Hummer/Classes/Engine/N-API/HMJSExecutor.h
- iOS/Hummer/Classes/Engine/N-API/HMJSExecutor.m
> fix(iOS): executor support  multi handler for console & exception

- tenon/packages/tenon-vue/src/runtime/nodes/components/text.ts
> feat(tenon): 支持Text嵌套Text

- iOS/Hummer/Classes/Core/Utility/HMConverter.m
> fix(iOS): Add content-box as value

- iOS/Hummer/Classes/Component/Controller/HMRootViewLifeCycle.h
- iOS/Hummer/Classes/Component/Controller/HMRootViewLifeCycle.m
- iOS/Hummer/Classes/Component/Controller/HMViewController.m
> fix(iOS): life cycle

- iOS/Hummer/Classes/Engine/HMBaseValue.m
> fix(iOS): HMBaseValue hasProperty use globalObject insteadof self

- iOS/Hummer/Classes/Component/WebSocket/HMWebSocket.m
> fix(iOS): Hummer webSocket component build error

- Hummer.podspec
- iOS/App.xcodeproj/project.pbxproj
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
- iOS/Hummer/Classes/Core/Layout/RenderObject/HMYogaUtility.h
- iOS/Podfile
- iOS/Podfile.lock
| Tests Added + Pass?      | No 
1. RN Hummer 并存模式，使用 `pod 'Hummer', :subspecs => ['RN']` 或者不添加 subspecs 指令也可以，framework 模式下也会出现编译错误
2. Hummer 开源 Yoga 模式，使用 `pod 'Hummer', :subspecs => ['OSSYoga']` 或者不添加 subspecs 指令，但是 framework 模式下会出现编译错误
> fix(iOS): Add RN yoga support

- iOS/Hummer/Classes/Component/Controller/HMViewController.h
- iOS/Hummer/Classes/Component/Controller/HMViewController.m
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Utility/Category/NSString+Hummer.h
- iOS/Hummer/Classes/Core/Utility/Category/NSString+Hummer.m
- iOS/Hummer/Classes/Core/Utility/HMDefines.h
- iOS/Hummer/Classes/Core/Utility/HMDefines.m
- iOS/Hummer/Classes/Dev/HMDebugService.m
- iOS/Hummer/Classes/Dev/HMDevGlobalWebSocket.h
- iOS/Hummer/Classes/Dev/HMDevGlobalWebSocket.m
- iOS/Hummer/Classes/Dev/HMDevService.h
- iOS/Hummer/Classes/Dev/HMDevService.m
> feat(iOS): reuse dev websocket

- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsHierarchyView/HMDevToolsHierarchyViewController.h
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsHierarchyView/HMDevToolsHierarchyViewController.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsMenuItem.h
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsMenuItem.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsViewController.m
DevTool： 用户点击“视图树” 的时，获取视图层级关系并显示
> feat(iOS)：DevTool工具 视图树刷新机制

- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsLogger/HMDevToolsLoggerViewController.m
console.error / exception 展示内容为 红色
> feat(iOS)：Dev工具，console.error / exception 展示内容为 红色

- iOS/Hummer/Classes/Component/Views/ListView/HMRecycleListView.m
- iOS/Hummer/Classes/Component/Views/Scroller/HMScrollView.m
> fix(iOS): Fix scroll begin event offset property

- iOS/Hummer/Classes/Component/Interface/HMRequestComponent.h
- iOS/Hummer/Classes/Component/Network/HMRequest.m
- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevPageInfo/HMDevPageInfoViewController.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevPageInfo/HMDevToolsJSCallerExecutor.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsViewController.m
- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsViewControllerProtocol.h
- iOS/Hummer/Classes/Dev/ViewInspector/View/NSObject+HMDescription.h
- iOS/Hummer/Classes/Dev/ViewInspector/View/NSObject+HMDescription.m
- iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
- iOS/Hummer/Classes/Engine/N-API/HMJSExecutor.m
- iOS/Hummer/Classes/Interceptor/Optimize/HMConfigEntryManager.h
- iOS/Hummer/Classes/Interceptor/Optimize/HMConfigEntryManager.m
> feat(iOS): devTool, request adaptor

- iOS/Hummer/Classes/Dev/DevTools/HMDevToolsLogger/HMDevToolsLoggerCell.m
> fix(iOS): devtool约束冲突问题解决

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
- iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
- iOS/Hummer/Classes/Interceptor/HMPluginManager.h
> feat(iOS): Add burry point

- iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
> feat(iOS): Add whiteScreenRate burry point.

- iOS/Hummer/Classes/Component/Views/View/HMAttributesItem.m
> fix(iOS): Chinese font does not contain italic variant.

- android/hummer-component/src/main/java/com/didi/hummer/component/button/Button.java
- android/hummer-component/src/main/java/com/didi/hummer/component/input/HMInputProperty.java
- android/hummer-component/src/main/java/com/didi/hummer/component/input/Input.java
- android/hummer-component/src/main/java/com/didi/hummer/component/text/FontManager.java
- android/hummer-component/src/main/java/com/didi/hummer/component/text/RichTextHelper.java
- android/hummer-component/src/main/java/com/didi/hummer/component/text/Text.java
- android/hummer-demo-app/src/main/java/com/didi/hummer/demo/App.java
- android/hummer-demo-app/src/main/java/com/didi/hummer/demo/TestFontAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/HummerConfig.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/font/IFontAdapter.java
- android/hummer-sdk/src/main/java/com/didi/hummer/adapter/font/impl/DefaultFontAdapter.java
> 扩展字体适配器，支持全局设置

- iOS/Hummer/Classes/Component/Views/Label/HMLabel.m
> feat(iOS): Add italic for Text font property.

- android/hermes-debugger/gradle.properties
| Major: Breaking Change?  | Yes
> chore(Android): android release version: hermes-debugger: 0.0.9

- iOS/Hummer/Classes/Component/Navigator/HMNavigator.m
> fix(iOS): Navigation interceptor pass view controller instead of nil.

- android/hummer-component/src/main/java/com/didi/hummer/component/button/Button.java
Button组件增加设置字重功能，设置fontWeight即可修改Button内部文字的字重
> feat(Android): Button component adds the function of setting  fontweight
